### ISSUE TITLE
How to Upgrade version R4 to R5 of existing open source fhir server

### ISSUE THREAD

**Issue by abhishek14anandDev** [microsoft/fhir-server#2465] opened 2022-02-01 10:25 UTC
**Describe the bug**
I want to upgrade the version to R5 from R4.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
SQL Server

**To Reproduce**
Want to upgrade the 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Comment by CaitlinV39** [comment] 2022-02-01 15:54
@abhishek14anandDev - We don't have a way to upgrade from one FHIR version to another. We haven't started looking at this yet. I'll leave this open as a user story but this isn't a bug, more of a feature request. 

@ranvijaykumar FYI

**Comment by abhishek14anandDev** [comment] 2022-02-01 17:54
okay, My problem is, _typeFilter was not supporting in earlier builds but now it is supporting. and i want to update my open source fhir server with current builds. 
Please let me know how to do that.

**Comment by abhishek14anandDev** [comment] 2022-02-12 03:50
@CaitlinV39  your reply would help me to decide. requesting you to reply on this

**Comment by CaitlinV39** [comment] 2022-02-15 18:52
I believe this is a duplicate of https://github.com/microsoft/fhir-server/issues/2483

**Closed by CaitlinV39** 2022-02-15 18:52 UTC
Labels: Epic
