### ISSUE TITLE
opened fhir server link auto downloding for all resourcesType(webbrowser)

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#817] opened 2020-01-14 09:11 UTC
Dear @hansenms 

i added successfully my fhir-server with azure portal but when i try to open a fhie server link as below it is auto downloading pop up is coming.

![image](https://user-images.githubusercontent.com/51785654/72329601-0e11b280-36db-11ea-9496-5a0145399886.png)

for Example:-  
case :  when i click on below URL-

https://fhirserver.net/metadata   //auto downloading in fhir-xml format
https://fhirserver.net/Patient    //auto downloading in fhir-xml format

below we are getting below file when after auto download.

![image](https://user-images.githubusercontent.com/51785654/72330246-2a621f00-36dc-11ea-9f8b-392458bc3237.png)

as per my and your expectation is this https://fhirserver.net/metadata link will open in same browser.

but this is not happening?

Note : i checked with all different machine and browser also.

Thanks
HadoopHelp

**Comment by hansenms** [comment] 2020-01-14 16:21
Use Postman. The browser will ask for XML output...probably. You can also add `_format` to the query URL:

```
GET https://<myfhirserver>.azurewebsites.net/metadata?_format=application/json
```

To force JSON.

closing this, since it is not a bug or issue on the server.

**Closed by hansenms** 2020-01-14 16:21 UTC
Labels: Resolution-Won't fix

**Comment by rameshkr1994** [comment] 2020-01-14 17:24
grand salute @hansenms 


I am your big follower .




Thanks
HadoopHelp
