### ISSUE TITLE
No handling of _revinclude=Observation:subject:NotAResourceType

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1251] opened 2020-09-09 16:08 UTC
Issue query
`Patient/?_revinclude=Observation:subject:NotAResourceType`

Result:
``` 
System.Collections.Generic.KeyNotFoundException: The given key 'NotAResourceType' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirModel.GetResourceTypeId(String resourceTypeName) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\SqlServerFhirModel.cs:line 74
   at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.VisitTable(TableExpression tableExpression, SearchOptions context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\Visitors\QueryGenerators\SqlQueryGenerator.cs:line 383
   at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.TableExpression.AcceptVisitor[TContext,TOutput](ISqlExpressionVisitor`2 visitor, TContext context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\TableExpression.cs:line 88
   at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.<>c__DisplayClass16_0.<VisitSqlRoot>b__0(IndentedStringBuilder sb, TableExpression tableExpression) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\Visitors\QueryGenerators\SqlQueryGenerator.cs:line 65
   at Microsoft.Health.SqlServer.IndentedStringBuilder.AppendDelimited[T](String delimiter, IEnumerable`1 items, Action`2 writer)
   at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.VisitSqlRoot(SqlRootExpression expression, SearchOptions context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\Visitors\QueryGenerators\SqlQueryGenerator.cs:line 59
   at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.SqlRootExpression.AcceptVisitor[TContext,TOutput](ISqlExpressionVisitor`2 visitor, TContext context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\SqlRootExpression.cs:line 65
   at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchImpl(SearchOptions searchOptions, Boolean historySearch, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\SqlServerSearchService.cs:line 179
   at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchInternalAsync(SearchOptions searchOptions, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\SqlServerSearchService.cs:line 113
   at Microsoft.Health.Fhir.Core.Features.Search.SearchService.SearchAsync(String resourceType, IReadOnlyList`1 queryParameters, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Search\SearchService.cs:line 52
   at Microsoft.Health.Fhir.Core.Features.Search.SearchResourceHandler.Handle(SearchResourceRequest message, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\SearchResourceHandler.cs:line 54
   at Microsoft.Health.Fhir.Core.Features.Search.Behavior.ListSearchPipeBehavior.Handle(SearchResourceRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\Behaviors\ListSearchPipeBehavior.cs:line 63
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Microsoft.Health.Fhir.Core.Extensions.FhirMediatorExtensions.SearchResourceAsync(IMediator mediator, String type, IReadOnlyList`1 queries, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Extensions\FhirMediatorExtensions.cs:line 70
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.PerformSearch(String type, IReadOnlyList`1 queries) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 485
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.SearchByResourceType(String typeParameter) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 414
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Api.Modules.InitializationModule.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextAfterAuthenticationMiddleware.Invoke(HttpContext context, IFhirRequestContextAccessor fhirRequestContextAccessor) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextAfterAuthenticationMiddleware.cs:line 36
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextBeforeAuthenticationMiddleware.Invoke(HttpContext context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextBeforeAuthenticationMiddleware.cs:line 45
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 63
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 90
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 52
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Health.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)


```

**Comment by CaitlinV39** [comment] 2020-09-22 00:02
AB#76141

**Comment by EXPEkesheth** [comment] 2022-10-05 19:44
@johnstairs , thanks for reporting the issue . The issue is now fixed.

**Closed by EXPEkesheth** 2022-10-05 19:44 UTC
Labels: Bug, VSTS-Backlog
