### ISSUE TITLE
Getting 500 on patient GET

### ISSUE THREAD

**Issue by EMellau** [microsoft/fhir-server#2349] opened 2021-11-11 09:38 UTC
### When calling Fhir with `_summary=` and `organization.identifier=` as params on Patient resource get, I get a 500.
![SEARCH_BY_PARTICIPANT_AND_SUBJECT_ORG_ID](https://user-images.githubusercontent.com/45633709/141274995-9a632868-e24e-4b8e-aaca-93f380a77208.png)
![SEARCH_BY_PARTICIPANT](https://user-images.githubusercontent.com/45633709/141275005-825203a1-28c2-485f-80d4-962c1f07e938.png)

**Comment by brendankowitz** [comment] 2021-11-12 03:11
Thanks for reporting this @EMellau. This case here is caused by a sub-query throwing an exception in Cosmos, we'll look into fixing this. 

Though there is still a bug happening here, just be aware that there is currently an upper limit of 1000 items that can be returned in the sub-query filters. So in the above example, the query will eventually limit 1000 Patient ids that are linked from the Organization. The OSS SQL implementation and Azure Healthcare APIs (different to Azure API for FHIR) don't have this limitation.

**Comment by CaitlinV39** [comment] 2021-11-12 18:35
AB#86619

**Comment by CaitlinV39** [comment] 2021-12-16 17:36
This is merged so closing. Please let us know if you are still having any issues.

**Closed by CaitlinV39** 2021-12-16 17:36 UTC
Labels: Bug, VSTS-Current
