### ISSUE TITLE
Transaction failure error message should be more specific

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#896] opened 2020-02-21 02:34 UTC
**Describe the bug**
Executed a transaction and it failed with message "Operation was not attempted because search criteria was not selective enough.". 

However, the message is not specific enough to figure out where the problem is. Since it's 412, I think it's because conditional create failed due to multiple matches but there are multiple conditional create within the transaction. It would be nice to know which one failed.

Request Body:
``` json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:b2813ca8-a6b3-43db-bfc6-fc16e8a145cb",
            "resource": {
                "resourceType": "Patient",
                "identifier": [
                    {
                        "system": "",
                        "value": "D97258/11053"
                    }
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Rubo DEMO"
                    }
                ],
                "gender": "other"
            },
            "request": {
                "method": "POST",
                "url": "Patient",
                "ifNoneExist": "identifier=D97258/11053"
            }
        },
        {
            "fullUrl": "urn:uuid:6ab9dad5-c2c7-43fc-b18a-59d7dde306f9",
            "resource": {
                "resourceType": "Encounter",
                "status": "finished",
                "class": {
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                    "code": "ambulatory"
                },
                "subject": {
                    "reference": "urn:uuid:b2813ca8-a6b3-43db-bfc6-fc16e8a145cb"
                }
            },
            "request": {
                "method": "POST",
                "url": "Encounter"
            }
        },
        {
            "fullUrl": "urn:uuid:5329868e-95ab-47f6-aca1-cfeded99be0e",
            "resource": {
                "resourceType": "ImagingStudy",
                "identifier": [
                    {
                        "system": "urn:dicom:uid",
                        "value": "urn:oid:UNKNOWN"
                    }
                ],
                "status": "available",
                "modality": [
                    {
                        "system": "DCM",
                        "code": "XA"
                    }
                ],
                "subject": {
                    "reference": "urn:uuid:b2813ca8-a6b3-43db-bfc6-fc16e8a145cb"
                },
                "encounter": {
                    "reference": "urn:uuid:6ab9dad5-c2c7-43fc-b18a-59d7dde306f9"
                },
                "started": "1997-04-22T13:10:47-08:00"
            },
            "request": {
                "method": "POST",
                "url": "ImagingStudy",
                "ifNoneExist": "urn:dicom:uid|urn:oid:UNKNOWN"
            }
        }
    ]
}
```

Response:
```
HTTP/1.1 412 Precondition Failed
Content-Length: 222
Content-Type: application/fhir+json; charset=utf-8

{"resourceType":"OperationOutcome","id":"b7c26ed6-06bb-43bf-9a31-73ed652221b8","issue":[{"severity":"error","code":"required","diagnostics":"Operation was not attempted because search criteria was not selective enough."}]}

```

**Expected behavior**
Error message should indicate which item failed.

**Actual behavior**
Error message indicate there was a problem but hard to debug.

Looking at the request, I think it failed because of the last entry where the IfNoneExist condition is not valid (I forgot to add identifier=urn:dicom:uid|urn:old:UNKNOWN) so it matched multiple resources but it would be nice to be able to pin point which one that caused the failure.

**Comment by evachen96** [comment] 2024-10-16 19:10
This issue has been resolved. The current actual behavior matches the expected behavior, which indicates the specific failed item from the bundle resource. @EXPEkesheth this one can be closed!

**Comment by EXPEkesheth** [comment] 2024-10-16 21:25
Closing as the issue is addressed.

**Closed by EXPEkesheth** 2024-10-16 21:25 UTC
Labels: Enhancement, Up for grabs, Review
