### ISSUE TITLE
Composite search fails with missing second parameter

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#824] opened 2020-01-14 23:26 UTC
**Describe the bug**
When a composite search is performed without a second parameter it fails with a 500. 
The examples given fails on the null check at the start of the Parse method in TokenSearchValue.cs (line 62), but other paths may exist as well. 

**To Reproduce**
The following URLs produce the error: 
GET [base]/Group?characteristic-value=gender$
GET [base]/Group?characteristic-value=gender,

**Expected behavior**
There is no reference in the spec for what to do in this case, https://www.hl7.org/fhir/search.html#combining, so I think returning a 401 would be correct.

**Actual behavior**
Returns a 500

**Comment by v-shnarang** [comment] 2024-10-04 07:38
@EXPEkesheth : This issue should be close as we are not able to reproduce it and also getting the expected output

**Comment by EXPEkesheth** [comment] 2024-10-14 22:58
Closing with the comment above

**Closed by EXPEkesheth** 2024-10-14 22:58 UTC
Labels: Area-Search, Up for grabs, Review
