### ISSUE TITLE
ServiceUnavailableException when SQL AutomaticUpdatesEnabled is disabled

### ISSUE THREAD

**Issue by PaulRReynolds** [microsoft/fhir-server#3195] opened 2023-03-27 12:08 UTC
**Describe the bug**
When `SchemaOptions.AutomaticUpdatesEnabled` is disabled, the application won't respond to requests, and returns a message: "The operation could not be completed, because the service was unable to accept new requests". The cause appears to be a `ServiceUnavailableException` thrown in: `SqlServerFhirModel.ThrowIfNotInitialized`. The method refers to the variable `_highestInitializedVersion`, however when AutomaticUpdatesEnabled is disabled, the `Initialize` method is never called, so the variable remains at 0. If AutomaticUpdatesEnabled is re-enabled, the app starts correctly and responds to requests.

I'm on Tag: release/3.4.57 (Schema version 50)

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Start the app with a SQL Conn String for a non-existent database (same error occurs for existing)
2. Ensure that Automatic Schema Updates are enabled
3. Start the app, and wait a while for migrations and Initialization to run
4. Stop the app, and disable Automatic Schema Updates
5. Start the app, and call the /metadata endpoint. Notice an error Operation Outcome is returned

I've also tried waiting a couple of minutes in case the Schema Manager task should run and initialize, however this makes no difference.

**Expected behavior**
I expect to be able to disable Automatic Schema Updates in my production environment, and have the app start up and respond to requests.

**Actual behavior**
Currently, a `ServiceUnavailableException` is thrown in `SqlServerFhirModel.ThrowIfNotInitialized` Line 455

AB#101927

**Comment by EXPEkesheth** [comment] 2023-03-29 22:16
@rbans96 - can you please help review the issue and help understand the next step here?

**Comment by EXPEkesheth** [comment] 2023-03-31 00:21
@PaulRReynolds - Thanks for reporting the issue! We will take steps to fix the issue and inform once fix is available.

**Comment by EXPEkesheth** [comment] 2023-04-03 16:53
@PaulRReynolds - the issue is fixed with https://github.com/microsoft/fhir-server/pull/3209. Please let us know if you have additional questions..

**Closed by EXPEkesheth** 2023-04-03 16:53 UTC
Labels: Bug, Review, VSTS-Current
