### ISSUE TITLE
SQL Exception 8623 The query processor ran out of internal resources and could not produce a query plan

### ISSUE THREAD

**Issue by akatakritos** [microsoft/fhir-server#2818] opened 2022-09-22 13:32 UTC
**Describe the bug**
Hi, we're running this service in Azure PaaS as the "Azure Health Data Services - FHIR" and recently started getting this exception on a query that used to work fine. This is reproducible in both our QA and Production environments.

> Operation was unsuccessful, and returned status InternalServerError. OperationOutcome: Overall result: FAILURE (1 errors and 0 warnings)
>[ERROR] (no details)(further diagnostics: SqlException number: 8623; Exception: The query processor ran out of internal resources and could not produce a query plan. This is a rare event and only expected for extremely complex queries or queries that reference a very large number of tables or partitions. Please simplify the query. If you believe you have received this message in error, contact Customer Support Services for more information.). 

GET https://host/ServiceRequest?_count=20&_include=ServiceRequest%3Apatient&_include=ServiceRequest%3Aspecimen&_sort=-_lastUpdated&resultStatus=Closed&intent=original-order&status=active%2Ccompleted%2Cunknown&collectionDate=gt2022-05-31&collectionDate=lt2022-05-31T23:59&subject%3APatient.address-state%3Aexact=AL%2CAS%2CAZ%2CAR%2CCA%2CCO%2CCT%2CDE%2CDC%2CFL%2CGA%2CGU%2CHI%2CID%2CIL%2CIN%2CIA%2CKS%2CKY%2CLA%2CME%2CMD%2CMA%2CMI%2CMN%2CMS%2CMO%2CMT%2CNE%2CNV%2CNH%2CNJ%2CNM%2CNY%2CNC%2CND%2CMP%2COH%2COK%2COR%2CPA%2CPR%2CRI%2CSC%2CSD%2CTN%2CTX%2CUT%2CVT%2CVI%2CVA%2CWA%2CWV%2CWI%2CWY%2CAK%2CUNKNOWN&category%3Anot=Toxicology&_total=accurate 

I'm not quite sure if its related to the number of parameters or the combination of them. Removing `category:not` still fails, but removing one of the others causes it to pass.

Some of those search params are custom ones, but from my udnerstanding of the FHIR Server architecture, theres no real difference in database schema design between a custom and built in SearchParam. But they are defined as follows:

- resultStatus: type: token  expression: "ServiceRequest.extension.where(url = 'https://example.com/service-request/result-status-extension').where(value = 1).extension.where(url = 'https://example.com/service-request/result-status-extension/result-status').value.code"

- collectionDate type: date expression: "ServiceRequest.extension.where(url = 'https://example.com/service-request/collection-date-extension').value"

Also opened an azure support ticket - 2209220040000451

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
I'm not quite sure if this is related to the amount of data, but we only have ~1,800 ServiceRequest records (plus their histories) in production, and its reproducible in QA which I think is <500.

1. Issue a search query like above
2. 
3. 

**Expected behavior**
This should return results, not crash the underlying SQL Server

**Actual behavior**
Received a failure OperationOutcome with an error message about running out of query plan resources

AB#95713

**Comment by akatakritos** [comment] 2022-09-22 16:14
This gnarly thing seems to be the query. Running the search against a debug empty database in my local environment. 

```sql
      DECLARE @p0 SmallInt = 1376;
      DECLARE @p1 VarChar(128) = 'Closed';
      DECLARE @p2 SmallInt = 124;
      DECLARE @p3 SmallInt = 1260;
      DECLARE @p4 VarChar(128) = 'original-order';
      DECLARE @p5 SmallInt = 1269;
      DECLARE @p6 VarChar(128) = 'active';
      DECLARE @p7 VarChar(128) = 'completed';
      DECLARE @p8 VarChar(128) = 'unknown';
      DECLARE @p9 SmallInt = 1380;
      DECLARE @p10 DateTime2 = '2022-05-31T23:59:59.9999999Z';
      DECLARE @p11 DateTime2 = '2022-05-31T23:59:00.0000000Z';
      DECLARE @p12 SmallInt = 1270;
      DECLARE @p13 SmallInt = 103;
      DECLARE @p14 SmallInt = 688;
      DECLARE @p15 NVarChar(256) = N'AL';
      DECLARE @p16 NVarChar(256) = N'AS';
      DECLARE @p17 NVarChar(256) = N'AZ';
      DECLARE @p18 NVarChar(256) = N'AR';
      DECLARE @p19 NVarChar(256) = N'CA';
      DECLARE @p20 NVarChar(256) = N'CO';
      DECLARE @p21 NVarChar(256) = N'CT';
      DECLARE @p22 NVarChar(256) = N'DE';
      DECLARE @p23 NVarChar(256) = N'DC';
      DECLARE @p24 NVarChar(256) = N'FL';
      DECLARE @p25 NVarChar(256) = N'GA';
      DECLARE @p26 NVarChar(256) = N'GU';
      DECLARE @p27 NVarChar(256) = N'HI';
      DECLARE @p28 NVarChar(256) = N'ID';
      DECLARE @p29 NVarChar(256) = N'IL';
      DECLARE @p30 NVarChar(256) = N'IN';
      DECLARE @p31 NVarChar(256) = N'IA';
      DECLARE @p32 NVarChar(256) = N'KS';
      DECLARE @p33 NVarChar(256) = N'KY';
      DECLARE @p34 NVarChar(256) = N'LA';
      DECLARE @p35 NVarChar(256) = N'ME';
      DECLARE @p36 NVarChar(256) = N'MD';
      DECLARE @p37 NVarChar(256) = N'MA';
      DECLARE @p38 NVarChar(256) = N'MI';
      DECLARE @p39 NVarChar(256) = N'MN';
      DECLARE @p40 NVarChar(256) = N'MS';
      DECLARE @p41 NVarChar(256) = N'MO';
      DECLARE @p42 NVarChar(256) = N'MT';
      DECLARE @p43 NVarChar(256) = N'NE';
      DECLARE @p44 NVarChar(256) = N'NV';
      DECLARE @p45 NVarChar(256) = N'NH';
      DECLARE @p46 NVarChar(256) = N'NJ';
      DECLARE @p47 NVarChar(256) = N'NM';
      DECLARE @p48 NVarChar(256) = N'NY';
      DECLARE @p49 NVarChar(256) = N'NC';
      DECLARE @p50 NVarChar(256) = N'ND';
      DECLARE @p51 NVarChar(256) = N'MP';
      DECLARE @p52 NVarChar(256) = N'OH';
      DECLARE @p53 NVarChar(256) = N'OK';
      DECLARE @p54 NVarChar(256) = N'OR';
      DECLARE @p55 NVarChar(256) = N'PA';
      DECLARE @p56 NVarChar(256) = N'PR';
      DECLARE @p57 NVarChar(256) = N'RI';
      DECLARE @p58 NVarChar(256) = N'SC';
      DECLARE @p59 NVarChar(256) = N'SD';
      DECLARE @p60 NVarChar(256) = N'TN';
      DECLARE @p61 NVarChar(256) = N'TX';
      DECLARE @p62 NVarChar(256) = N'UT';
      DECLARE @p63 NVarChar(256) = N'VT';
      DECLARE @p64 NVarChar(256) = N'VI';
      DECLARE @p65 NVarChar(256) = N'VA';
      DECLARE @p66 NVarChar(256) = N'WA';
      DECLARE @p67 NVarChar(256) = N'WV';
      DECLARE @p68 NVarChar(256) = N'WI';
      DECLARE @p69 NVarChar(256) = N'WY';
      DECLARE @p70 NVarChar(256) = N'AK';
      DECLARE @p71 NVarChar(256) = N'UNKNOWN';
      DECLARE @p72 SmallInt = 1257;
      DECLARE @p73 VarChar(128) = 'Toxicology';
      DECLARE @p74 Int = 21;
      DECLARE @p75 SmallInt = 217;
      DECLARE @p76 Int = 21;
      DECLARE @p77 SmallInt = 1268;
      DECLARE @p78 Int = 21;
      
      SET STATISTICS IO ON;
      SET STATISTICS TIME ON;
      
      WITH cte0 AS
      (
          SELECT ResourceTypeId AS T1, ResourceSurrogateId AS Sid1
          FROM dbo.TokenSearchParam
          WHERE IsHistory = 0
              AND SearchParamId = @p0
              AND Code = @p1
              AND ResourceTypeId = @p2
          
      ),
      cte1 AS
      (
          SELECT ResourceTypeId AS T1, ResourceSurrogateId AS Sid1
          FROM dbo.TokenSearchParam
          WHERE IsHistory = 0
              AND EXISTS(SELECT * FROM cte0 WHERE ResourceTypeId = T1 AND ResourceSurrogateId = Sid1)
              AND SearchParamId = @p3
              AND Code = @p4
              AND ResourceTypeId = @p2
          
      ),
      cte2 AS
      (
          SELECT ResourceTypeId AS T1, ResourceSurrogateId AS Sid1
          FROM dbo.TokenSearchParam
          WHERE IsHistory = 0
              AND EXISTS(SELECT * FROM cte1 WHERE ResourceTypeId = T1 AND ResourceSurrogateId = Sid1)
              AND SearchParamId = @p5
              AND ((Code = @p6)
              OR (Code = @p7)
              OR (Code = @p8))
              
              AND ResourceTypeId = @p2
          
      ),
      cte3 AS
      (
          SELECT ResourceTypeId AS T1, ResourceSurrogateId AS Sid1
          FROM dbo.DateTimeSearchParam
          WHERE IsHistory = 0
              AND EXISTS(SELECT * FROM cte2 WHERE ResourceTypeId = T1 AND ResourceSurrogateId = Sid1)
              AND SearchParamId = @p9
              AND EndDateTime > @p10
              AND ResourceTypeId = @p2
          
      ),
      cte4 AS
      (
          SELECT ResourceTypeId AS T1, ResourceSurrogateId AS Sid1
          FROM dbo.DateTimeSearchParam
          WHERE IsHistory = 0
              AND EXISTS(SELECT * FROM cte3 WHERE ResourceTypeId = T1 AND ResourceSurrogateId = Sid1)
              AND SearchParamId = @p9
              AND StartDateTime < @p11
              AND ResourceTypeId = @p2
          
      ),
      cte5 AS
      (
          SELECT refSource.ResourceTypeId AS T1, refSource.ResourceSurrogateId AS Sid1, refTarget.ResourceTypeId AS T2, refTarget.ResourceSurrogateId AS Sid2 
          FROM dbo.ReferenceSearchParam refSource
          INNER JOIN dbo.Resource refTarget
          ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
              AND refSource.ReferenceResourceId = refTarget.ResourceId
          WHERE refSource.SearchParamId = @p12
              AND refTarget.IsHistory = 0
              AND refSource.IsHistory = 0
              AND refSource.ResourceTypeId IN (@p2)
              AND refSource.ReferenceResourceTypeId IN (@p13)
              AND EXISTS(SELECT * FROM cte4 WHERE refSource.ResourceTypeId = T1 AND refSource.ResourceSurrogateId = Sid1)
              AND refSource.ResourceTypeId = @p2
      ),
      cte6 AS
      (
          SELECT T1, Sid1, ResourceTypeId AS T2, 
          ResourceSurrogateId AS Sid2
          FROM dbo.StringSearchParam
          INNER JOIN cte5
          ON ResourceTypeId = T2
              AND ResourceSurrogateId = Sid2
          WHERE IsHistory = 0
              AND SearchParamId = @p14
              AND ((Text = @p15 AND Text = @p15 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p16 AND Text = @p16 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p17 AND Text = @p17 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p18 AND Text = @p18 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p19 AND Text = @p19 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p20 AND Text = @p20 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p21 AND Text = @p21 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p22 AND Text = @p22 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p23 AND Text = @p23 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p24 AND Text = @p24 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p25 AND Text = @p25 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p26 AND Text = @p26 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p27 AND Text = @p27 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p28 AND Text = @p28 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p29 AND Text = @p29 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p30 AND Text = @p30 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p31 AND Text = @p31 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p32 AND Text = @p32 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p33 AND Text = @p33 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p34 AND Text = @p34 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p35 AND Text = @p35 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p36 AND Text = @p36 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p37 AND Text = @p37 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p38 AND Text = @p38 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p39 AND Text = @p39 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p40 AND Text = @p40 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p41 AND Text = @p41 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p42 AND Text = @p42 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p43 AND Text = @p43 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p44 AND Text = @p44 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p45 AND Text = @p45 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p46 AND Text = @p46 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p47 AND Text = @p47 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p48 AND Text = @p48 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p49 AND Text = @p49 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p50 AND Text = @p50 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p51 AND Text = @p51 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p52 AND Text = @p52 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p53 AND Text = @p53 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p54 AND Text = @p54 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p55 AND Text = @p55 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p56 AND Text = @p56 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p57 AND Text = @p57 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p58 AND Text = @p58 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p59 AND Text = @p59 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p60 AND Text = @p60 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p61 AND Text = @p61 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p62 AND Text = @p62 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p63 AND Text = @p63 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p64 AND Text = @p64 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p65 AND Text = @p65 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p66 AND Text = @p66 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p67 AND Text = @p67 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p68 AND Text = @p68 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p69 AND Text = @p69 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p70 AND Text = @p70 COLLATE Latin1_General_100_CS_AS)
              OR (Text = @p71 AND Text = @p71 COLLATE Latin1_General_100_CS_AS))
          
      ),
      cte7 AS
      (
          SELECT T1, Sid1
          FROM cte6
          WHERE Sid1 NOT IN
          (
              SELECT ResourceSurrogateId
              FROM dbo.TokenSearchParam
              WHERE IsHistory = 0
                  AND SearchParamId = @p72
                  AND Code = @p73
                  AND ResourceTypeId = @p2
              
          )
      ),
      cte8 AS
      (
          SELECT ROW_NUMBER() OVER(ORDER BY T1 DESC, Sid1 DESC) AS Row, *
          FROM
          (
              SELECT DISTINCT TOP (@p74) T1, Sid1, 1 AS IsMatch, 0 AS IsPartial 
              FROM cte7
              ORDER BY T1 DESC, Sid1 DESC
          ) t
      ),
      cte9 AS
      (
          SELECT DISTINCT refTarget.ResourceTypeId AS T1, refTarget.ResourceSurrogateId AS Sid1, 0 AS IsMatch 
          FROM dbo.ReferenceSearchParam refSource
          INNER JOIN dbo.Resource refTarget
          ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
              AND refSource.ReferenceResourceId = refTarget.ResourceId
          WHERE refSource.SearchParamId = @p75
              AND refTarget.IsHistory = 0
              AND refSource.IsHistory = 0
              AND refTarget.IsDeleted = 0
              AND refSource.ResourceTypeId IN (124)
              AND EXISTS( SELECT * FROM cte8 WHERE refSource.ResourceTypeId = T1 AND refSource.ResourceSurrogateId = Sid1 AND Row < @p76)
      ),
      cte10 AS
      (
          SELECT DISTINCT T1, Sid1, IsMatch, 0 AS IsPartial 
          FROM cte9
      ),
      cte11 AS
      (
          SELECT DISTINCT refTarget.ResourceTypeId AS T1, refTarget.ResourceSurrogateId AS Sid1, 0 AS IsMatch 
          FROM dbo.ReferenceSearchParam refSource
          INNER JOIN dbo.Resource refTarget
          ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
              AND refSource.ReferenceResourceId = refTarget.ResourceId
          WHERE refSource.SearchParamId = @p77
              AND refTarget.IsHistory = 0
              AND refSource.IsHistory = 0
              AND refTarget.IsDeleted = 0
              AND refSource.ResourceTypeId IN (124)
              AND EXISTS( SELECT * FROM cte8 WHERE refSource.ResourceTypeId = T1 AND refSource.ResourceSurrogateId = Sid1 AND Row < @p78)
      ),
      cte12 AS
      (
          SELECT DISTINCT T1, Sid1, IsMatch, 0 AS IsPartial 
          FROM cte11
      ),
      cte13 AS
      (
          SELECT T1, Sid1, IsMatch, IsPartial 
          FROM cte8
          UNION ALL
          SELECT T1, Sid1, IsMatch, IsPartial
          FROM cte10 WHERE NOT EXISTS (SELECT * FROM cte8 WHERE cte8.Sid1 = cte10.Sid1 AND cte8.T1 = cte10.T1)
          UNION ALL
          SELECT T1, Sid1, IsMatch, IsPartial
          FROM cte12 WHERE NOT EXISTS (SELECT * FROM cte8 WHERE cte8.Sid1 = cte12.Sid1 AND cte8.T1 = cte12.T1)
      )
      SELECT DISTINCT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, CAST(IsPartial AS bit) AS IsPartial, r.IsRawResourceMetaSet, r.SearchParamHash, r.RawResource
      FROM dbo.Resource r
      
      INNER JOIN cte13
      ON r.ResourceTypeId = cte13.T1 AND 
      r.ResourceSurrogateId = cte13.Sid1
      ORDER BY IsMatch DESC, r.ResourceTypeId DESC, r.ResourceSurrogateId DESC
      /* HASH trLX6drA9Hx98kjN10+jvlrFneXL9XCjGvDBcN3OuPg= */

```

**Comment by akatakritos** [comment] 2022-09-23 13:47
#2819 possibly related -- query planning inside of SQL Server in general seems to be a cause of significant slowdowns in responses. SQL server is reporting a fast execution time (10ms) but its still taking 4000+ms of clock time to get a SQL results back (even an empty one!)

**Comment by EXPEkesheth** [comment] 2022-09-23 18:08
@akatakritos Thanks for reporting the issue ! We will take a look and get back,

**Comment by idrisfl** [comment] 2022-10-23 17:24
We are migrating our existing application to the new generation of FHIR (Azure Health Data Services) and we have encountered the same error as @akatakritos

### Request:
`GET {{FHIR_HostName}}/?journeyId={{JOURNEYID_GUID}}&userId={{USERID_GUID}}&serviceId={{SERVICEID_GUID}}&_count=500&_total=accurate`

### Response:
`500 Internal Server Error : {"resourceType":"OperationOutcome","id":"8c72e7d8e1344baa9d58b9baea2d3f78","meta":{"lastUpdated":"2022-10-23T15:38:54.7962948+00:00"},"issue":[{"severity":"error","code":"exception","diagnostics":"SqlException number: 8623; Exception: The query processor ran out of internal resources and could not produce a query plan. This is a rare event and only expected for extremely complex queries or queries that reference a very large number of tables or partitions. Please simplify the query. If you believe you have received this message in error, contact Customer Support Services for more information."}]}`

- Removing a combination of the custom search parameters in the request works fine
- Same scenario works fine with the previous generation of the FHIR resource service (Azure API for FHIR)

**Comment by EXPEkesheth** [comment] 2023-01-09 18:27
@akatakritos , @idrisfl - Thanks for reporting the issue. The issue is addressed with PR https://github.com/microsoft/fhir-server/pull/2978. Let us know if you have any further questions,

**Comment by EXPEkesheth** [comment] 2023-03-06 05:33
Reopening the issue, as we had to revert the change due to performance issue identified with the fix.

**Comment by EXPEkesheth** [comment] 2023-05-26 21:21
Closing issue . Please let us know if you have any further questions related to fix.

**Closed by EXPEkesheth** 2023-05-26 21:21 UTC
Labels: Bug, VSTS-Current
