### ISSUE TITLE
_include search param doesn't work with compartmentalized query

### ISSUE THREAD

**Issue by sasireha** [microsoft/fhir-server#2826] opened 2022-09-26 14:11 UTC
**Description:**
When retrieving performer resource references from Observation resource using the following query, it returns 500 internal server error.

`GET [baseURL]/Patient/[id]/Observation?_include=Observation:performer:Practitioner `

**FHIR Version**
Stu3

**Data provider**
SQL Server

**Steps to reproduce:**
Try to retrieve the all the Observation resources along with the performer resource references of type Practitioner using the following compartmentalized query.

`GET [baseURL]/Patient/[id]/Observation?_include=Observation:performer:Practitioner `

**Expected behaviour:**
Fhir server should return all the Observation along with the Practitioner resources.

**Actual Behaviour:**
FHIR server returns Internal server error with the following response

```
{
    "resourceType": "OperationOutcome",
    "id": "67b2dcc3-f6b1-4464-8310-b44946b1cc53",
    "meta": {
        "lastUpdated": "2022-09-26T13:57:21.8684784+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "unknown",
            "diagnostics": ""
        }
    ]
}
```

and FHIR server logs the following exception

```
      
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Microsoft.Health.Fhir.Api.Controllers.FhirController.SearchCompartmentByResourceType (Microsoft.Health.Fhir.Stu3.Api) - Validation state: Valid
fail: Microsoft.Health.Fhir.Api.Features.Filters.OperationOutcomeExceptionFilterAttribute[0]
      InternalServerError error returned
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'IncludeLimit')
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.<FindRestrictingPredecessorTableExpressionIndex>g__FindImpl|43_0(Int32 currentIndex) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 1155
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.FindRestrictingPredecessorTableExpressionIndex() in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 1159
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.HandleTableKindNormal(SearchParamTableExpression searchParamTableExpression, SearchOptions context) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 397
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.VisitTable(SearchParamTableExpression searchParamTableExpression, SearchOptions context) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 284
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.SearchParamTableExpression.AcceptVisitor[TContext,TOutput](ISqlExpressionVisitor`2 visitor, TContext context) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/SearchParamTableExpression.cs:line 59
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.AppendNewTableExpression(IndentedStringBuilder sb, SearchParamTableExpression tableExpression, Int32 cteId, SearchOptions context) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 1105
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.<>c__DisplayClass23_0.<VisitSqlRoot>b__0(IndentedStringBuilder sb, SearchParamTableExpression tableExpression) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 97
         at Microsoft.Health.SqlServer.IndentedStringBuilder.AppendDelimited[T](String delimiter, IEnumerable`1 items, Action`2 writer)
         at Microsoft.Health.Fhir.SqlServer.Features.Search.Expressions.Visitors.QueryGenerators.SqlQueryGenerator.VisitSqlRoot(SqlRootExpression expression, SearchOptions context) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/Expressions/Visitors/QueryGenerators/SqlQueryGenerator.cs:line 88
         at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchImpl(SqlSearchOptions sqlSearchOptions, SqlSearchType searchType, String currentSearchParameterHash, CancellationToken cancellationToken) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs:line 307
         at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchAsync(SearchOptions searchOptions, CancellationToken cancellationToken) in /fhir-server/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs:line 107
         at Microsoft.Health.Fhir.Core.Features.Search.SearchService.SearchCompartmentAsync(String compartmentType, String compartmentId, String resourceType, IReadOnlyList`1 queryParameters, CancellationToken cancellationToken, Boolean isAsyncOperation) in /fhir-server/src/Microsoft.Health.Fhir.Core/Features/Search/SearchService.cs:line 67
         at Microsoft.Health.Fhir.Core.Features.Search.SearchCompartmentHandler.Handle(SearchCompartmentRequest request, CancellationToken cancellationToken) in /fhir-server/src/Microsoft.Health.Fhir.Core/Features/Compartment/SearchCompartmentHandler.cs:line 54
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at Microsoft.Health.Fhir.Core.Extensions.FhirMediatorExtensions.SearchResourceCompartmentAsync(IMediator mediator, String compartmentType, String compartmentId, String resourceType, IReadOnlyList`1 queries, CancellationToken cancellationToken) in /fhir-server/src/Microsoft.Health.Fhir.Shared.Core/Extensions/FhirMediatorExtensions.cs:line 131
         at Microsoft.Health.Fhir.Api.Controllers.FhirController.PerformCompartmentSearch(String compartmentType, String compartmentId, String resourceType, IReadOnlyList`1 queries) in /fhir-server/src/Microsoft.Health.Fhir.Shared.Api/Controllers/FhirController.cs:line 537
         at Microsoft.Health.Fhir.Api.Controllers.FhirController.SearchCompartmentByResourceType(String compartmentTypeParameter, String idParameter, String typeParameter) in /fhir-server/src/Microsoft.Health.Fhir.Shared.Api/Controllers/FhirController.cs:line 532
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

AB#95810

**Comment by EXPEkesheth** [comment] 2022-10-14 18:31
Thankyou @sasireha for reporting the issue, We will take a look.

**Comment by aignatovich** [comment] 2022-10-28 10:32
According to my findings the issue appeared after commit [24226e485e30fbd24ae89d84e49ee06653cc94f2](https://github.com/microsoft/fhir-server/commit/24226e485e30fbd24ae89d84e49ee06653cc94f2).

 Specifically after [CompartmentSearchRewriter.cs](https://github.com/microsoft/fhir-server/commit/24226e485e30fbd24ae89d84e49ee06653cc94f2#diff-f9d25ad03b97e1928c6c84a8c26475a31e9c2002b1214085a2ea3651954be991) was added to the chain of visitors in [SqlServerSearchService.cs](https://github.com/microsoft/fhir-server/commit/24226e485e30fbd24ae89d84e49ee06653cc94f2#diff-f3916a4983b586e1856684444fac2e85b32b42ccb2c406cf02e8dd69738c0b64).
 
 Removing this rewriter solves the issue.
 Could @fhibf (original author of the commit) bring some clarity on the acceptable approach to solve the issue?

**Comment by EXPEkesheth** [comment] 2022-11-23 23:28
@sasireha - Thanks for reporting the issue. The issue is fixed with latest OSS release.
Please feel free to reach out for any additional information needed.

**Closed by EXPEkesheth** 2022-11-23 23:28 UTC
Labels: Bug
