### ISSUE TITLE
Error in New-FhirServerApiApplicationRegistration Powershell script

### ISSUE THREAD

**Issue by Echostorm44** [microsoft/fhir-server#2784] opened 2022-08-30 19:02 UTC
**Describe the bug**
Following along with the documentation on this page:
https://github.com/Microsoft/fhir-server/blob/main/docs/DefaultDeployment.md

When I execute the command:
$apiAppReg = New-FhirServerApiApplicationRegistration -FhirServiceName $fhirServiceName -AppRoles globalAdmin
in an admin powershell window after connecting successfully using Connect-AzureAD and setting the var like so:
$fhirServiceName = "myfhirservice"
I get this exception
Get-ServiceAudience : The term 'Get-ServiceAudience' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\users\adamm\source\repos\MSFhirServer\fhir-server\samples\scripts\PowerShell\FhirServer\Public\New-FhirServerApiApplicationRegistration.ps1
:51 char:32
+         $FhirServiceAudience = Get-ServiceAudience -ServiceName $Fhir ...
+                                ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ServiceAudience:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Pretty screenshot version:
![image](https://user-images.githubusercontent.com/107306362/187520319-86558d02-8210-4d90-91a3-ea6d4a1393cc.png)

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. open an admin powershell instance and get to the fhirserver folder
2. run--- Import-Module .\samples\scripts\PowerShell\FhirServer\FhirServer.psd1
3. then---  $fhirServiceName = "myfhirservice"
4. and finally --- $apiAppReg = New-FhirServerApiApplicationRegistration -FhirServiceName $fhirServiceName -AppRoles globalAdmin

**Expected behavior**
Not to throw exception

**Actual behavior**
Throws exception despite me saying please

AB#94785

**Comment by EXPEkesheth** [comment] 2022-08-30 22:36
@Echostorm44 - thanks for reporting, we will look into the issue and get back.

**Comment by EXPEkesheth** [comment] 2022-12-05 06:52
@Echostorm44 - thanks for reporting the issue. The issue is now fixed. Please reach out for any additional questions.

**Closed by EXPEkesheth** 2022-12-05 06:52 UTC
Labels: Bug
