### ISSUE TITLE
while adding the "id":"myid",getting Exception: This resource already has an id, cannot create

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#818] opened 2020-01-14 15:58 UTC
Dear @hansenms 

i am trying to create patient records from reading the json file and condition is: 
 in this json file  i am providing  own id value but this value is not accepting fhir server and displaying below error:-

![image](https://user-images.githubusercontent.com/51785654/72359130-bb082180-3713-11ea-9afd-77807852974a.png)

Below is my json data:-
`{
    "resourceType": "Patient",
    "active": true,
	"id":"abc01",
    "name": [
        {
            "use": "official",
            "family": "family",
            "given": [
                "hivefile",
                "sy"
            ]
        },
        {
            "use": "usual",
            "given": [
                "hivefile sy"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "2010-12-19"
}`

when i remove that id value it is working

Note:-we  want to replace the id value with My patient HRK value.

Thanks
HadoopHelp

**Comment by hansenms** [comment] 2020-01-14 16:25
If you want to bring your own IDs, you have to do a PUT instead of a POST. So say you want to create a patient with a specific `id` (e.g. `1234`), you would do:

```
PUT https://myfhirservice/Patient/1234
```

with a payload of:

```
{
  "resourceType": "Patient",
  "id": "1234",

    // ... other fields 
}
```

If the resource exists, it will be updated, otherwise created. See FHIR upsert (https://www.hl7.org/fhir/http.html#upsert).

Closing this, since it is not a bug or issue with the server.

**Closed by hansenms** 2020-01-14 16:25 UTC
Labels: Resolution-Won't fix

**Comment by rameshkr1994** [comment] 2020-01-14 17:18
Thanks @hansenms .

i will try this way....




Thanks
HadoopHelp

**Comment by rameshkr1994** [comment] 2020-01-16 07:27
Hi @hansenms .

i treied below code but getting same issue.

`#y = requests.post(url, data1, 'application/fhir+json') //with post same issue
        
y = requests.put(url, data1, 'application/fhir+json')` //with put same issue

image Exception : -
![image](https://user-images.githubusercontent.com/51785654/72502554-9de06980-385f-11ea-9d77-85b81a8515fa.png)


Thanks.
HadoopHelp

**Comment by hansenms** [comment] 2020-01-16 13:29
This error message does not come from our server, it comes from the python FHIR client. I don't think anything is ever sent to the server. I would suggest debugging the issue in the FHIR client and raising an issue with them if there is a a problem. If you are thinking that a request is made to the server and it is handled incorrectly, please use Fiddler or something to capture the request and we can have a look.

It is not possible for us dig into this, but the error appears to come from here: https://github.com/smart-on-fhir/client-py/blob/master/fhirclient/models/fhirabstractresource.py#L114 so when 'create' is called. However, if you scroll down a bit, you will see there is an `update` method, which I think it what should be called when you are doing a PUT and in fact it explicitly checks that the resource has an `id` before updating.

So 1) I don't think you call ever gets to the server, and 2) I don't think your call turns into an `update`.

Again, any issues with the python client is probably better handled over on that repo.
