### ISSUE TITLE
History request in Bundle returns 404

### ISSUE THREAD

**Issue by LodewijkSioen** [microsoft/fhir-server#3821] opened 2024-04-22 11:24 UTC
**Describe the bug**

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
Create a patient resource and copy the ID.

This works:
```
GET Patient/{patientid}/_history
```

This doesn't
```
POST http://localhost:8080
Content-Type: application/json

{"resourceType":"Bundle","type":"batch","entry":[{"request":{"method":"GET","url":"Patient/{patientid}/_history"}}]}
```
**Expected behavior**
I would expect a bundle with an entry containing a bundle with the history of the resource

**Actual behavior**
```
{
  "resourceType": "Bundle",
  "type": "batch-response",
  "entry": [
    {
      "response": {
        "status": "404",
        "outcome": {
          "resourceType": "OperationOutcome",
          "issue": [
            {
              "severity": "error",
              "code": "not-found",
              "diagnostics": "The route for \"/Task/fdcfb035-6dc3-421a-8675-415fc31f9fc7/_history\" was not found."
            }
          ]
        }
      }
    }
  ]
}
```

[AB#119362](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/119362)

**Comment by mikaelweave** [comment] 2024-04-22 17:41
Hi @LodewijkSioen! I just ran a quick test and confirmed I'm seeing this issue on my system.

**Comment by brendankowitz** [comment] 2024-04-22 18:23
Quickly looked through the trace, looks like it matches 2 routes: Resource History, the correct route and CompartmentSearch. After that is goes into this method to resolve and ends up returning null. I'm wondering if it isn't evaluating the route parameter constraints either.

https://github.com/microsoft/fhir-server/blob/f9e520c29353b2327c7a51454a84266364ffdb48/src/Microsoft.Health.Fhir.Shared.Api/Features/Resources/Bundle/BundleRouter.cs#L117-L147

**Comment by EXPEkesheth** [comment] 2024-05-28 17:44
@LodewijkSioen  Closing as the issue is addressed

**Closed by EXPEkesheth** 2024-05-28 17:44 UTC
Labels: Bug
