### ISSUE TITLE
link to self not matching request link when fhir-server behind proxy

### ISSUE THREAD

**Issue by luckyluc74** [microsoft/fhir-server#1080] opened 2020-06-12 12:38 UTC
**Describe the bug**
The fhir-server is running behind proxy in kubernetes with internal domain http://fhir-server.
The internet domain where the fhir server is reachable is https://myserver.com/fhir

Now when I make a Get request for all patient records  to url
https://myserver.com/fhir/Patient/

The link to self is  
http://fhir-server/Patient

instead of
https://myserver.com/fhir/Patient

Part of fhir response
```
{
    "resourceType": "Bundle",
    "id": "9f376f78-ed21-4b2b-8aba-0550b8d00a41",
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "http://fhir-server/Patient"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://fhir-server/Patient/test-patient1",
            "resource": {
                "resourceType": "Patient",
                "id": "test-patient1",
```

**To Reproduce**
1. setup fhir-server behind proxy with an example patient record with domain http://fhir-server
2. make fhir-server reachable from external domain https://myserver.com/fhir/Patient/
3. make get request to https://myserver.com/fhir/Patient/

**Expected behavior**
Get request for all patient records  to url with
https://myserver.com/fhir/Patient

Should have link to self  
https://myserver.com/fhir/Patient

**Actual behavior**
Get request for all patient records to url with
https://myserver.com/fhir/Patient

link to self  is
http://fhir-server/Patient

**Comment by hansenms** [comment] 2020-06-12 16:50
Can you try to get the environment variable `ASPNETCORE_FORWARDEDHEADERS_ENABLED` to `true`.

Also, please check the helm chart we just merged:

https://github.com/microsoft/fhir-server/tree/master/samples/kubernetes

**Comment by luckyluc74** [comment] 2020-06-29 20:15
@hansenms thanks for suggestion, I will try that options and report back if it worked.

Great that there is also a helm chart , will check that for sure!

**Comment by luckyluc74** [comment] 2020-07-23 14:59
I tested it with variable `ASPNETCORE_FORWARDEDHEADERS_ENABLED` to `true`. 

```
"environmentVariables": {
    // left out other env variables for clarity
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true",
},
```

This only fixes the scheme of url. 
Now it uses `https `instead of `http `which is correct.

Only 2 issues are left to fix

1. hostname
2. path

FYI changes below are made in project `Microsoft.Health.Fhir.Stu3.Web`

To fix the hostname I added ` ForwardedHeaders.XForwardedHost` to `ForwardedHeadersOptions`
 in method `public virtual void ConfigureServices(IServiceCollection services)` in class `Startup.cs`

like this
```
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor |
        ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;

    // Only loopback proxies are allowed by default.
    // Clear that restriction because forwarders are enabled by explicit
    // configuration.
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});
```

To fix the trimmed proxy path I added following code 
to method  `public virtual void Configure(IApplicationBuilder app)` in class  `Startup.cs`

```
// If the proxy trims the path
// (for example, forwarding /foo/api/1 to /api/1), fix redirects and links by setting the request's PathBase property:
if (!string.IsNullOrEmpty(Configuration["PROXY_TRIM_PATH"]))
{
    app.Use(async (context, next) =>
    {
        context.Request.PathBase = new PathString(Configuration["PROXY_TRIM_PATH"]);
        await next.Invoke();
    });
}
```
For more information about proxy paths in combination with aspnetcore 3.1 see following [offical documentation from microsoft](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1)

This is just a working draft, would ofcoursce be better to have it in own middleware with `app.UseTrimmedProxyPath ` for example.

I added following environment variabele to `launchSettings.json`

```
"environmentVariables": {
    // left out other env variables for clarity
     "PROXY_TRIM_PATH": "/fhir",
 },
```

Now with above changed 'link to self is' is correct in Patient response.

**Comment by luckyluc74** [comment] 2020-07-23 15:03
Extra, if the proxy adds a path instead of trimming path you can use following code to fix 'link to self' urls in reponse

```
// If the proxy is adding path data
if (!string.IsNullOrEmpty(Configuration["PROXY_ADD_PATH"]))
{
    app.Use((context, next) =>
    {
        if (context.Request.Path.StartsWithSegments(Configuration["PROXY_ADD_PATH"], out var remainder))
        {
            context.Request.Path = remainder;
        }

        return next();
    });
}
```

This is just a working draft, would ofcoursce be better to have it in own middleware with app.UseAddedProxyPath for example.

I added following environment variabele to `launchSettings.json`
```
"environmentVariables": {
    // left out other env variables for clarity
     "PROXY_ADD_PATH": "/test",
 },
```

**Comment by luckyluc74** [comment] 2020-07-23 15:07
@hansenms  Are these fixes likely candidates to be merged with fhir-server?

**Comment by luckyluc74** [comment] 2020-07-23 15:34
Possible implementation of middleware `app.UseTrimmedProxyPath`

```
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;

namespace Example.Middleware
{
    public static class ApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseTrimmedProxyPath(this IApplicationBuilder app)
        {
            return app.UseMiddleware<TrimmedProxyPathMiddleware>();
        }
    }

    public class TrimmedProxyPathMiddleware
    {
        private readonly RequestDelegate _next;

        public TrimmedProxyPathMiddleware(RequestDelegate next, IConfiguration configuration)
        {
            _next = next;
            Configuration = configuration;
        }

        private IConfiguration Configuration { get; }

        public async Task InvokeAsync(HttpContext context)
        {
            if (context != null)
            {
                context.Request.PathBase = new PathString(Configuration["PROXY_TRIM_PATH"]);
            }
            await _next(context);
        }
    }
}
```

**Comment by hansenms** [comment] 2020-07-23 15:58
I think the bigger issue right now is that I cannot reproduce the problem. When using our helm chart to provision the service behind nginx ingress controller, the hostname is correct. I did not try with a path segment since it is not a scenario we target at the moment, but we can investigate. So I think we would not merge the changes until we understand what the problem is and we would have to have testing, etc. added as well. 

Are you deploying with our helm chart or some other mechanism?

**Comment by luckyluc74** [comment] 2020-07-23 16:22
Currently I use a custom made helm chart' of fhir-server made before there was an official helm chart of fhir-server. We also use a custom proxy. I will try if I can reproduce it with nginx ingres and official helm chart of fhir-server. I will also test it with traeffic ingress and official helm chart of fhir-server. 

@hansenms if possible that you could share the configuration of the nginx ingress controller you used?

**Comment by hansenms** [comment] 2020-07-23 16:25
The Kubernetes cluster setup we use is all described here:
https://github.com/microsoft/fhir-server/tree/master/samples/kubernetes

**Comment by luckyluc74** [comment] 2020-07-23 16:35
Thanks for info! 

It would be nice if there would be a sample kubernetes setup to use in local kubernetes cluster like k3s/docker desktop without dependencies to azure.

**Comment by hansenms** [comment] 2020-07-23 16:37
You can provision the helm chart on minikube too. I have done it. It works, but I did not test the ingress stuff there.

**Comment by anyname2** [comment] 2020-08-18 20:29
#1200 should fix the path issue (in all the places links appear, not just `self`)

**Comment by CaitlinV39** [comment] 2020-09-14 18:54
@luckyluc74 I wanted to check if you still have any questions on this? If not I'll close the issue. Thanks!

**Closed** 2020-09-22 00:10 UTC
Labels: Area-Deployment, Feedback-Pending acceptance
