### ISSUE TITLE
IIS configuration cache cleanup stalling fhir-server

### ISSUE THREAD

**Issue by klimkjar** [microsoft/fhir-server#2674] opened 2022-06-22 10:14 UTC
**Describe the bug**
We are running MS fhir-server 2.2.95 scaled to two instances with a CosmosDB backend (direct connection mode). We are occasionally seeing hangs / stalls in one or both instances, sometimes resolving by themselves after 5-10 mins, other times triggering autoheal and application restart after 15 minutes. We earlier attributed the hangs to the CosmosDB provider but this seems to have been a red herring. We've been working with Microsoft Azure Support to help debug this with the help of some memory dumps captured while the stalls are occurring. As per their analysis,

> ...the problem seems to be a huge number of configuration elements that are cached by IIS configuration reader system. Once the cache size is exceeded and the configuration reader tries to reduce that size by getting rid of stalled configuration data, All HTTP request traffic execution within the application is blocked until the cache is cleaned.

This cleanup stalls all incoming requests, typically for 5-15 minutes. The configuration elements are from the `/RelatedPerson` and `/Patient` controllers, which are the resources we have the most traffic on.

Attaching the dump analysis as well.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Run fhir-server normally for a while
2. ???
3. incoming requests eventually start timing out, until fhir-server starts responding again or is restarted automatically by Azure auto-heal

**Expected behavior**
fhir-server does not stop responding unless requests are causing load beyond what the application is scaled to handle

**Actual behavior**
fhir-server hangs intermittently from time to time once the IIS configuration cache has filled up

[dump_analysis.txt](https://github.com/microsoft/fhir-server/files/8956599/dump_analysis.txt)

[AB#92920](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/92920)

**Comment by fhibf** [comment] 2022-06-22 16:38
Hi, @klimkjar.
I'll start testing this issue.
I'm going to update as soon as I have an update or more questions. 

Thanks.

**Comment by fhibf** [comment] 2022-06-30 21:57
Hi, @klimkjar.

Questions to help us simulating this issue: 
- What is the volume of data and number of requests sent to FHIR?
- Is this service hosted in an Azure Windows web app? I'm asking it, because I noticed the mention about Azure Auto-heal. 
- If this is a Azure Web App, I believe it's a Docker container with Windows. Is that correct?

**Comment by klimkjar** [comment] 2022-07-01 12:30
Hi @fhibf , and thank you for looking into this.

* On a typical day we see ~3M requests, ~20GB data in and ~30GB data out. The total CosmosDB size is ~1TB of data and ~200GB of indexes.
* The service is hosted in an Azure App Service (Windows). We are not using Docker containers.

**Comment by fhibf** [comment] 2022-07-21 21:36
Hi, @klimkjar.

I've tried reproducing this issue in two different ways:
* Hosting an instance of FHIR on Azure App Service (with Windows).
* Hosting an instance of FHIR on IIS locally.

In both cases the applications have been working well with more than 24hs of continuous requests. 

I also took few memory dumps and I was not able to see a thread stuck into the configuration load. 

Do you mind sharing more configuration details + auto-healing configuration? 

Thanks.

**Comment by klimkjar** [comment] 2022-07-22 10:41
Hi @fhibf - 24 hours is typically not enough to reproduce this. We usually see the stalls occurring after 1-3 weeks of continuous requests. Auto-heal settings do not seem to impact the stalls, when the memory dumps were captured auto-heal was turned off to give us time to trigger the captures before the app restarted.

We're running under the P3v2 app service plan. The web.config is here:
[webconfig.txt](https://github.com/microsoft/fhir-server/files/9166900/webconfig.txt)

Environment settings are here (sensitive settings redacted):
![config_1](https://user-images.githubusercontent.com/11939107/180422026-486e2114-8af5-453b-a7bc-d7c1926a13d2.PNG)
![config_2](https://user-images.githubusercontent.com/11939107/180422045-0ef643da-ec40-4f38-8529-58f7a1c1f3e8.PNG)

Autoscale settings are here:
![autoscale](https://user-images.githubusercontent.com/11939107/180422442-1ba78a5a-9c79-4288-852b-02d7242fea67.png)

We're happy to provide other configuration details on request if necessary.

**Comment by klimkjar** [comment] 2022-07-22 10:48
For completeness, here are the autoheal settings. No custom autoheal rules are defined.
![autoheal](https://user-images.githubusercontent.com/11939107/180423860-9fc81200-9d84-48ed-bc74-e9c830ced410.PNG)

**Comment by fhibf** [comment] 2022-08-11 01:18
Hello, @klimkjar. Thanks for all the information. 

That's not a trivial issue: our team is in contact with the IIS team at this moment. 
We are working together to find the origin of the problem and provide a solution.

**Comment by EXPEkesheth** [comment] 2023-03-04 00:36
@klimkjar and @fhibf , I understand there was long term plan defined for this issue and there is no action Microsoft FHIR server side. Closing the issue and please feel free to contact us for any additional questions/ information needed. Thankyou.

**Closed by EXPEkesheth** 2023-03-04 00:36 UTC
Labels: Bug, Bug-Performance, Review
