### ISSUE TITLE
Validation error in Bundles using profiles

### ISSUE THREAD

**Issue by ikivanc** [microsoft/fhir-server#2312] opened 2021-11-02 14:08 UTC
**Describe the bug**
I've created a profile for a Patient resource, I enabled the validation whenever I create or update using
`x-ms-profile-validation: true` header.

Whenever I have missing fields defined in my resource based on profile, I retrieve an error telling that fields are missing in my resource. However when I try with Bundle it doesn't 

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Create a Patient profile with `gender` is required
2. Set your header `x-ms-profile-validation: true`
2. Post a Patient without `gender`
3. Retrieve a warning because of missing `gender` field
4. Create a Bundle includes Patient with a Profile`
5. Set your header `x-ms-profile-validation: true`
4. Post the Bundle includes Patient without `gender`
5. Server doesn't validate and creates resources automatically

**Expected behavior**
Validating the content using Profile and retrieving an error same as creating a Patient

**Actual behavior**
Server doesn't validate and creates resources automatically

**Comment by CaitlinV39** [comment] 2021-11-05 20:51
Thanks @ikivanc for reporting this. We will triage and update here as we determine timelines for updates.

**Comment by CraigP68** [comment] 2021-12-09 00:12
AB#87248

**Comment by EXPEkesheth** [comment] 2022-10-10 16:27
Thanks @ikivanc for reporting the issue. The issue is now fixed. Please let us know if you have any questions.

**Closed by EXPEkesheth** 2022-10-10 16:27 UTC
Labels: Bug, VSTS-Backlog
