### ISSUE TITLE
Integration Issue: Conflicting Functionality between DICOMCast and Smart on FHIR

### ISSUE THREAD

**Issue by HitakshiDobariya99** [microsoft/fhir-server#3638] opened 2023-11-07 13:48 UTC
I've successfully deployed [DICOM Cast](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-oss) and [SMART on FHIR](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md) in my Azure environment. However, I am encountering an integration issue related to the audience configuration.

During the deployment of DICOM Cast, The audience of the FHIR service to be the same as the FHIR service's endpoint, aligning with the default behavior.

Conversely, during the deployment of SMART on FHIR, the audience is set to the Application ID URI of the fhir-resource-app. This divergence in audience configuration is causing a conflict in integration.

To make DICOM Cast work, I need to align the FHIR service audience with the FHIR endpoint. However, doing so disrupts the functionality of SMART on FHIR.

Aligning the FHIR audience with the application ID URI of fhir-resource-app allows SMART on FHIR to work but breaks DICOM Cast.

I need guidance on how to reconcile these conflicting audience configurations to ensure the seamless integration of DICOM Cast and SMART on FHIR.

**Comment by EXPEkesheth** [comment] 2024-02-07 18:46
Closing this issue, as it duplicate of the issue : https://github.com/Azure-Samples/azure-health-data-and-ai-samples/issues/150 
Please follow on samples OSS repo for the latest.

**Closed by EXPEkesheth** 2024-02-07 18:46 UTC
