### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by mohan14r** [microsoft/fhir-server#993] opened 2020-04-23 18:57 UTC
**Describe the bug**

**To Reproduce**
1. env SAPASSWORD='root' docker-compose up -d . i have executed the command, i got below error.
2. 

> Building fhir-api
> Traceback (most recent call last):
>   File "docker-compose", line 6, in <module>
>   File "compose/cli/main.py", line 72, in main
>   File "compose/cli/main.py", line 128, in perform_command
>   File "compose/cli/main.py", line 1077, in up
>   File "compose/cli/main.py", line 1073, in up
>   File "compose/project.py", line 548, in up
>   File "compose/service.py", line 367, in ensure_image_exists
>   File "compose/service.py", line 1106, in build
>   File "site-packages/docker/api/build.py", line 160, in build
>   File "site-packages/docker/utils/build.py", line 30, in tar
>   File "site-packages/docker/utils/build.py", line 49, in exclude_paths
>   File "site-packages/docker/utils/build.py", line 214, in rec_walk
>   File "site-packages/docker/utils/build.py", line 214, in rec_walk
>   File "site-packages/docker/utils/build.py", line 214, in rec_walk
>   File "site-packages/docker/utils/build.py", line 184, in rec_walk
> PermissionError: [Errno 1] Operation not permitted: '/Users/<localUser>/Library/Application Support/CallHistoryTransactions'
> [2217] Failed to execute script docker-compose

3. Is it taking my call History 

**Expected behavior**
it should install, and run
**Actual behavior**
getting error to accessing

**Comment by hansenms** [comment] 2020-04-23 20:09
Not really sure what the problem is or whether it is related to the FHIR server at all. Looks like it could be a docker permission error. Are you able to execute other Docker commands? Like `docker ls` or `docker images`.  Looks like you are on a mac, so you may want to ensure that you are set up with the right permissions.

**Comment by brendankowitz** [comment] 2020-06-01 23:21
Closing this for now, it doesn't look like this issue relates specifically to our docker-compose scripts

**Closed by brendankowitz** 2020-06-01 23:21 UTC
Labels: Feedback-Need more info
